- name: 'Evento 1'
  image: '/torresgaleria.com/assets/img/001.jpg'
  href: ''
  desc: 'Alguna descripción'
  tag: promo
- name: 'Evento 2'
  image: '/torresgaleria.com/assets/img/002.jpg'
  href: ''
  desc: 'Alguna descripción'
  tag: promo
- name: 'Evento 3'
  image: '/torresgaleria.com/assets/img/002.jpg'
  href: ''
  desc: 'Alguna descripción'
  tag: promo
