- name: 'Evento 1'
  image: '/assets/img/001.jpg'
  href: ''
  desc: 'Alguna descripción'
  tag: promo
- name: 'Evento 2'
  image: '/assets/img/002.jpg'
  href: ''
  desc: 'Alguna descripción'
  tag: promo
- name: 'Evento 3'
  image: '/assets/img/002.jpg'
  href: ''
  desc: 'Alguna descripción'
  tag: promo
